openapi: 3.1.0
info:
  title: Swagger Chat - OpenAPI 3.1
  description: |-
    This is a sample Chat Server based on the OpenAPI 3.1 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). 

  contact:
    email: john@willard.pro
  version: 1.0.0
tags:
  - name: chat
    description: Everything about your chats
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /chat:
    post:
      tags:
        - chat
      summary: Adds a new message to the chat thread
      description: Adds a message to the chat thread
      operationId: addMessage
      requestBody:
        description: Add new message to chat
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserMessage'
        required: true
      responses:
        '200':
          description: Successful operation
        '405':
          description: Invalid input
  /chat/{userId}:
    get:
      tags:
        - chat
      summary: Find all messages in chat thread made by userId
      description: Returns all messages posted by userId on chat thread
      operationId: getMessages
      parameters:
        - name: userId
          in: path
          description: ID of user chats to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Messages'
        '400':
          description: Invalid ID supplied
        '404':
          description: UserId not found
components:
  schemas:
    Messages:
      items:
        $ref: '#/components/schemas/Message'
    Message:
      type: object
      required:
        - id
        - text
      properties:
        id:
          type: integer
          format: int64
          examples: [10]
        text:
          type: string
          description: Message sent by user
          examples: [Hallo World!]
    UserMessage:
      type: object
      required:
        - userId
        - text
      properties:
        userId:
          type: integer
          format: int64
          examples: [10]
        text:
          type: string
          description: Message sent by user
          examples: [Hallo World!]
